export const ptbr = {
    "startsWith": "Começa com",
    "contains": "Contém",
    "notContains": "Não contém",
    "endsWith": "Termina com",
    "equals": "Igual",
    "notEquals": "Diferente de",
    "noFilter": "Sem filtro",
    "lt": "Menor que",
    "lte": "Menor ou igual",
    "gt": "Maior que",
    "gte": "Maior ou igual",
    "is": "É",
    "isNot": "Não é",
    "before": "Antes",
    "after": "Depois",
    "clear": "Limpar",
    "apply": "Aplicar",
    "matchAll": "Combina com tudo",
    "matchAny": "Combina com qualquer",
    "addRule": "Adicionar regra",
    "removeRule": "Remover regra",
    "accept": "Sim",
    "reject": "Não",
    "choose": "Escolha",
    "upload": "Upload",
    "cancel": "Cancelar",
    "dayNames": ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"],
    "dayNamesShort": ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
    "dayNamesMin": ["Do", "Se", "Te", "Qa", "Qi", "Se", "Sá"],
    "monthNames": ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", " Dezembro"],
    "monthNamesShort": ["Jan", "Fev", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Set", "Out", "Nov", " Dez "],
    "today": "Hoje",
    "weekHeader": "Wk"
}

